### ISSUE TITLE
taxjar is not working for any of the method

### ISSUE THREAD

**Issue by heyupen** [taxjar/taxjar-php#16]
i have put all the taxjar required files for php using composer in vendor folder, vendor folder is in application/libraries/taxjar folder. my vendor folder structure is

                        vendor
                                  composer
                                  guzzlehttp
                                  psr
                                  taxjar
                                  autoload.php

i put just a simple code to calculate tax for an order and it is not returing anything. The code i placed is

`require_once($_SERVER['DOCUMENT_ROOT'].'/application/libraries/taxjar/vendor/autoload.php');

		$client = TaxJar\Client::withApiKey("[REDACTED]");

		$order_taxes = $client->taxForOrder([
  			'from_country' => 'US',
  			'from_zip' => '07001',
  			'from_state' => 'NJ',
  			'to_country' => 'US',
  			'to_zip' => '07446',
  			'to_state' => 'NJ',
  			'amount' => 16.50,
  			'shipping' => 1.5,
  			'line_items' => [
    			[
      				'quantity' => 1,
      				'unit_price' => 15.0,
      				'product_tax_code' => 31000
    			]
  			]
		]);
                var_dump($order_taxes);`

where have i gone wrong ?

**Comment by TiffanieL** [comment]
I attempted to reproduce this issue and received a valid API response. Could you please let me know if you are receiving any response or errors at all, and copy them here? It may help to add the following to the top of your script:
```
ini_set('display_errors', 1);
error_reporting(E_ALL);
```

Could you let us know what version of PHP are you using? We do recommend that you use the latest version of our client as well.

Another possibility is that there is a server or proxy issue, but we do not have enough information to know for sure.

Additionally, would you mind sending details from a simple 'phpinfo()' page so we can review your configuration?

Please reach out to support@taxjar.com so we can also look directly at your account for more details.

Thank you
