### ISSUE TITLE
Problem 1     - The requested package taxjar/taxjar-php No version set (parsed as 1.0.0) is satisfiable by taxjar/taxjar-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

### ISSUE THREAD

**Issue by ajkosh** [taxjar/taxjar-php#22]
getting this error when installing 
Problem 1
    - The requested package taxjar/taxjar-php No version set (parsed as 1.0.0) is satisfiable by taxjar/taxjar-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by fastdivision** [comment]
@ajkosh If you get an error with `composer require`, update your `composer.json` file directly and then run `composer update`:

```json
{
  "require": {
    "taxjar/taxjar-php": "^1.8"
  }
}
```

If you continue to have issues, would you mind sharing your `composer.json` file? Thank you!

**Comment by fastdivision** [comment]
@ajkosh Did the suggestion above resolve your issue? Let me know, thanks!

**Comment by ajkosh** [comment]
Sorry for late reply
No still it is not working.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package taxjar/taxjar-php No version set (parsed as 1.0.0) is satisfiable by taxjar/taxjar-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by fastdivision** [comment]
@ajkosh Could you please share your `composer.json` file? Thank you!

**Comment by ajkosh** [comment]
Yes it is working.Thank you for help.
