### ISSUE TITLE
Set default timeout

### ISSUE THREAD

**Issue by fastdivision** [taxjar/taxjar-php#25]
[Default timeout](http://docs.guzzlephp.org/en/stable/request-options.html?highlight=timeout#timeout) with Guzzle is 0 seconds (indefinite). We should set a default timeout of 30 seconds and document how to customize the timeout via `setApiConfig` in the README.

**Comment by sethobey** [comment]
Closing issue as no longer planned.

For reference this functionality can be implemented as shown below, if desired: 

```php
require __DIR__ . '/vendor/autoload.php';
$client = TaxJar\Client::withApiKey("9e0cd62a22f451701f29c3bde214");

// Set Guzzle client timeout to 30 seconds
$client->setApiConfig('timeout', 30);
```
