### ISSUE TITLE
Null taxes for cross-state calculations

### ISSUE THREAD

**Issue by budhajeewa** [taxjar/taxjar-php#3]
I am currently evaluating TaxJar to use it with a custom e-commerce solution we develop for one of our clients.

We use the PHP API Client. Everything seems to work fine except for the following issue. Please not that the issue described below is not specific to the PHP API Client, because I get the same issue when accessing your API through cURL.

When I request tax to be calculated for an order with both sender's and receiver's locations in the same US state, it all works fine and I get a sensible result from the API. See the below cURL code and the result it yielded.

Request:

```
curl --request POST \
  --url https://api.taxjar.com/v2/taxes \
  --header 'authorization: Bearer {--API-KEY--}' \
  --header 'content-type: multipart/form-data; boundary=---011000010111000001101001' \
  --form from_country=US \
  --form from_zip=07001 \
  --form from_state=NJ \
  --form to_country=US \
  --form to_zip=07446 \
  --form to_state=NJ \
  --form amount=16.50 \
  --form shipping=1.5
```

Result:

```
{
   "tax":{
      "order_total_amount":18.0,
      "shipping":1.5,
      "taxable_amount":18.0,
      "amount_to_collect":1.26,
      "rate":0.07,
      "has_nexus":true,
      "freight_taxable":true,
      "tax_source":"destination"
   }
}
```

However, when I change the to_zip and to_state to be different than the from address, I get zeros for the tax values.

Request:

```
curl --request POST \
  --url https://api.taxjar.com/v2/taxes \
  --header 'authorization: Bearer {--API-KEY--}' \
  --header 'content-type: multipart/form-data; boundary=---011000010111000001101001' \
  --form from_country=US \
  --form from_zip=07001 \
  --form from_state=NJ \
  --form to_country=US \
  --form to_zip=20500 \
  --form to_state=DC \
  --form amount=16.50 \
  --form shipping=1.5
```

Result:

```
{
   "tax":{
      "taxable_amount":0.0,
      "amount_to_collect":0.0,
      "rate":0.0,
      "has_nexus":false,
      "freight_taxable":null,
      "tax_source":null
   }
}
```

If I again make the sender's state and zip to that of the receiver's, I get correct results. Why is that? Doesn't TaxJar support cross-state transactions?

**Comment by tonkapark** [comment]
First to be clear this is not an issue with the PHP client.

Now for understanding how nexus works with [SmartCalcs API](http://www.taxjar.com/api/).

When the To location is not in the same state as the From location nexus is not generally triggered. To support cross-state transactions, you would need to have nexus in both states. You can identify additional nexus states in the NexusAddresses parameter. TaxJar also supports having your addresses on file in TaxJar which would be the same as passing them in via NexusAddresses.

**Comment by budhajeewa** [comment]
@tonkapark : Thanks Matt! :+1:
