### ISSUE TITLE
Upcoming required header not included

### ISSUE THREAD

**Issue by rrehbein** [taxjar/taxjar-php#40]
From: https://go.taxjar.com/2021-02-Customer-API-Validation.html

> What is changing with TaxJar’s API?
> 
> TaxJar’s API has introduced versioning via a headers parameter, ‘x-api-version’.  The ‘x-api-version’ can be specified at your software integration’s level. The most recent version of this parameter is:
> 
> 
> ‘x-api-version’: ‘2020-08-07’

**Comment by fastdivision** [comment]
@rrehbein You can pass this new header manually using the `setApiConfig` method as shown below:

```php
require __DIR__ . '/vendor/autoload.php';
$client = TaxJar\Client::withApiKey("9e0cd62a22f451701f29c3bde214");

$client->setApiConfig('headers', [
  'x-api-version' => '2020-08-07'
]);
```

I'm going to keep this issue open as we are planning to set this version across our API clients and official integrations for consistency. If / when breaking changes beyond mathematical validation are implemented, this will be a requirement here.

**Comment by mishac** [comment]
Any word on this?  It's been over a year since the last comment and the library still doesn't support api versioning out of the box.

**Comment by note-do** [comment]
Hello, guys. We've received an e-mail from taxjar about forcing upgrade their clients to version 2022-01-24 on 31st of August 2022.

![Screenshot 07-21-2022 13 31 49](https://user-images.githubusercontent.com/40624282/181051969-4897c795-d872-4190-875b-83102499609e.png)

We use your php library as taxjar client and really want to continue using it. Our taxjar integration perfectly compatible with all actual taxjar version. So, my question are:
- what taxjar api version connect with your library?
- what will happen after 2022-08-31 if we'll still use your library without ability to set api version?

**Comment by jszobody** [comment]
This is pretty funny. TaxJar sends tons of notices including an alarming "FINAL NOTICE" today about the need to upgrade, and yet the official TaxJar PHP library isn't ready?

**Comment by note-do** [comment]
Two weeks ago I receive an answer for the question about default taxjar api behavior. So, if you haven't set the version (it equals to use this library), you will use the latest version of taxjar api. Share this info here. Maybe it may be helpful for someone.

**Comment by sethobey** [comment]
Hello everyone,

After some deliberation, it was decided that the `x-api-version` header will _not_ be implemented in out taxjar-php SDK for the time being. As @note-do was kind enough to comment above, API functionality will automatically default to the latest API version whenever an `x-api-header` value is not present on the request.

This means that no action is necessary unless your TaxJar implementation requires a specific API version for whatever reason, in which case we recommend implementing an approach similar to what @fastdivision [has provided above](https://github.com/taxjar/taxjar-php/issues/40#issuecomment-780272123).

You can read more about the various functionalities of specific API versions here if necessary: https://developers.taxjar.com/api/reference/#changelog

On behalf of the team, my apologies for the delayed response.
