### ISSUE TITLE
TaxJar\Client::listOrders() responds with non existing transaction IDs.

### ISSUE THREAD

**Issue by budhajeewa** [taxjar/taxjar-php#6]
When `TaxJar\Client::listOrders()` is called, it fetches the following response from your API:

Call:

``` php
$taxjar = \TaxJar\Client::withApiKey ( __API_KEY__ ) ;

$orders = $taxjar -> listOrders ( [
 'from_transaction_date' => '2015/01/01' ,
 'to_transaction_date' => '2015/12/31'
] ) ;
```

Response:

``` php
array:3 [
  0 => "123"
  1 => "5"
  2 => "6"
]
```

While there are transactions with Order IDs 5 and 6 displayed in your web interface's dashboard, there is no transaction with Order ID 123.

I suspect this has to do with the examples provided in the documentation. May be example data were accidentally hard coded into the system?

**Comment by fastdivision** [comment]
@budhajeewa Oops! This is something related to your account while I was assisting you over support. Should be fixed now.

**Comment by budhajeewa** [comment]
@fastdivision Thanks Jake! :)
