### ISSUE TITLE
TaxJar\Client->createOrder() throws "GuzzleHttp\Exception\ClientException" with "Client error: 406"

### ISSUE THREAD

**Issue by thanhtr** [taxjar/taxjar-php#8]
Hi,

I get the error when creating Order, this is the example of my "json_encode" array that I pass in to createOrder():

`{"transacion_id":"359","transaction_date":"2015\/10\/14","from_country":"US","from_zip":"75211","from_state":"TX","from_city":"Dallas","from_street":"4105 Rock Quarry Road, Suite 400","to_country":"US","to_zip":"36604","to_state":"Alabama","to_city":"Helsinki","to_street":"Suvilahdenkatu 9 C 65 ","amount":27.65,"shipping":5.99,"sales_tax":2.77,"line_items":[{"quantity":1,"product-identifier":50369578,"description":"Waste Pick-Up - Rainbow","unit_price":14.35},{"quantity":1,"product-identifier":50194451,"description":"Fashion Dispenser and Refill Bags","unit_price":13.3}]}`

What can be the problem?

Thank you very much for your help.

-Tung

**Comment by aleccarper** [comment]
Hi thanhtr,

It looks like you may have misspelled 'transaction_id'.  Could update that and try again?

**Comment by thanhtr** [comment]
Oh yeah I didn't notice that :).
Anyway now I get the 'Client error: 400'. This is my new "json_encode" request, one of them:

`{"transaction_id":"360","transaction_date":"2015\/10\/15","to_country":"US","to_zip":"36604","to_state":"Alabama","to_city":"Helsinki","to_street":"Suvilahdenkatu 9 C 65 ","amount":21.5,"shipping":5.99,"sales_tax":2.15,"line_items":[{"quantity":1,"product-identifier":50194580,"description":"Hot Spot Spray, 16 OZ","unit_price":21.5}]}`

**Comment by thanhtr** [comment]
One more test that I provide also "from_xx" params, the request got through. Hmm I wonder why I need to provide from_ params when I already set up my Nexus states in Taxjar Dashboard?

**Comment by fastdivision** [comment]
@thanhtr We've been looking into this issue, should have an update shortly from our engineers. For now, please provide `from` params if you can do so. Thanks for being patient!

**Comment by thanhtr** [comment]
@fastdivision don't worry :).
